### ISSUE TITLE
IAX device support missing

### ISSUE THREAD

**Issue by buzzdeee** [trulabs/puppet-asterisk#14]
It would be nice, if the module could handle/configure IAX devices, similar to sip devices.

I use an IAX softphone client, and it would be nice, if I could manage it with the puppet module.
Should the manifests/config/device.pp just enhanced, to support iax devices too? Just add the missing
parameters. And then in manifests/config.pp take care of managing the iax.conf file too?

Or create a standalone manifests/config/iaxdevice.pp file in order do do that?

Either way, let me know and I can go on implementing it.

cheers,
Sebastian

**Comment by runswithd6s** [comment]
If it is just missing parameters, I would be in favor of just adding those in. I recently saw another puppet module with more dynamic use of parameters and ERB templates in such a way that you didn't need to specify each one explicitly. That being said, it would be simple to refactor later on.

Something else you may want to consider when extending the module, create and push a feature branch in git. This allows you to update the PR to address comments or suggestions.

This works for me:

```
# oops... committed a change to mater, rename
git branch -m master newfeature
# Set up so I can pull truelabs/puppet-asterisk (master) branch - http so I can't push to it
git remote add upstream git https://github.com/trulabs/puppet-asterisk.git
# Rebase from upstream/master
git rebase upstream/master
# edit... looks good, time to push to my origin
git push -u origin newfeature
# Log in to github and create PR
```

**Comment by buzzdeee** [comment]
Thanks, I will next time use feature branches, instead of what I did for the OpenBSD support ;)

It's mostly only some missing parameters, and the initial "concat" statement missing in config.pp, so I'll then add them in.

**Comment by giavac** [comment]
+1 to just add the missing parameters into device.pp. Thanks @buzzdeee
